export const beerOptions = [
    { value: 'ocean', label: 'Ocean', color: '#00B8D9', isFixed: true },
    { value: 'blue', label: 'Blue', color: '#0052CC', isDisabled: true },
    { value: 'purple', label: 'Purple', color: '#5243AA' },
    { value: 'red', label: 'Red', color: '#FF5630', isFixed: true },
    { value: 'orange', label: 'Porter'},
    { value: 'yellow', label: 'Yellow', color: '#FFC400' },
    { value: 'green', label: 'Green', color: '#36B37E' },
    { value: 'forest', label: 'Forest', color: '#00875A' },
    { value: 'slate', label: 'Slate', color: '#253858' },
    { value: 'silver', label: 'Silver', color: '#666666' },
  ];
  
  export const styleArr = [
    "American Rye Ale or Lager",
    "American-Style Amber/Red Ale",
    "American-Style Barley Wine Ale",
    "American-Style Brown Ale",
    "American-Style Cream Ale or Lager",
    "American-Style Dark Lager",
    "American-Style Imperial Stout",
    "American-Style India Black Ale",
    "American-Style India Pale Ale",
    "American-Style Lager",
    "American-Style Light Lager",
    "American-Style Pale Ale",
    "American-Style Stout",
    "American-Style Strong Pale Ale",
    "Baltic-Style Porter",
    "Bamberg-Style Bock Rauchbier",
    "Belgian-Style Dark Strong Ale",
    "Belgian-Style Dubbel",
    "Belgian-Style Fruit Lambic",
    "Belgian-Style Pale Ale",
    "Belgian-Style Pale Strong Ale",
    "Belgian-Style Quadrupel",
    "Belgian-Style Tripel",
    "Belgian-Style White",
    "Classic English-Style Pale Ale",
    "Classic Irish-Style Dry Stout",
    "Dark American-Belgo-Style Ale",
    "English-Style Dark Mild Ale",
    "English-Style India Pale Ale",
    "English-Style Pale Mild Ale",
    "European Low-Alcohol Lager",
    "Extra Special Bitter",
    "Foreign (Export)-Style Stout",
    "French & Belgian-Style Saison",
    "Fruit Beer",
    "German-Style Brown Ale/Altbier",
    "German-Style Doppelbock",
    "German-Style Heller Bock/Maibock",
    "German-Style Oktoberfest",
    "German-Style Pilsener",
    "German-Style Schwarzbier",
    "Golden or Blonde Ale",
    "Herb and Spice Beer",
    "Imperial or Double India Pale Ale",
    "Imperial or Double Red Ale",
    "Irish-Style Red Ale",
    "Kellerbier - Ale",
    "Light American Wheat Ale or Lager",
    "Oatmeal Stout",
    "Old Ale",
    "Ordinary Bitter",
    "Other Belgian-Style Ales",
    "Out of Category",
    "Porter",
    "Pumpkin Beer",
    "Scotch Ale",
    "Scottish-Style Light Ale",
    "Smoke Beer",
    "South German-Style Hefeweizen",
    "South German-Style Weizenbock",
    "Special Bitter or Best Bitter",
    "Specialty Beer",
    "Specialty Honey Lager or Ale",
    "Strong Ale",
    "Sweet Stout",
    "Traditional German-Style Bock",
    "Vienna-Style Lager",
    "Winter Warmer",
    ];

    export const countryArr = [
      "United States",
      "United Kingdom",
      "Argentina",
      "Aruba",
      "Australia",
      "Austria",
      "Belgium",
      "Belize",
      "Brazil",
      "Canada",
      "China",
      "Colombia",
      "Croatia",
      "Cuba",
      "Czech Republic",
      "Denmark",
      "Egypt",
      "El Salvador",
      "England",
      "Estonia",
      "Finland",
      "France",
      "French Polynesia",
      "Germany",
      "Greece",
      "Guatemala",
      "Honduras",
      "Hungary",
      "India",
      "Ireland",
      "Israel",
      "Italy",
      "Jamaica",
      "Japan",
      "Kenya",
      "Korea",
      "Latvia",
      "Lithuania",
      "Macao",
      "Macedonia",
      "Mauritius",
      "Mexico",
      "Myanmar",
      "Namibia",
      "Netherlands",
      "New Zealand",
      "Norway",
      "Panama",
      "Philippines",
      "Poland",
      "Portugal",
      "Russia",
      "Sierra Leone",
      "Slovakia",
      "Spain",
      "Sri Lanka",
      "Sweden",
      "Switzerland",
      "Taiwan",
      "Thailand",
      "Togo",
  ]


  export const categoryArr = [
    "Belgian and French Ale",
    "British Ale",
    "German Ale",
    "German Lager",
    "Irish Ale",
    "North American Ale",
    "North American Lager",
    "Other Lager",
    "Other Style",
  ]